// <auto-generated />
using System;
using Helpdesk.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helpdesk.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305151044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("IsDone");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ChecklistItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoneAt = new DateTime(2026, 3, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            DueAt = new DateTime(2026, 3, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsDone = true,
                            TaskItemId = 1,
                            Title = "Check application logs"
                        },
                        new
                        {
                            Id = 2,
                            DueAt = new DateTime(2026, 3, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsDone = false,
                            TaskItemId = 1,
                            Title = "Reproduce the issue"
                        },
                        new
                        {
                            Id = 3,
                            DueAt = new DateTime(2026, 2, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsDone = false,
                            TaskItemId = 2,
                            Title = "Verify SMTP settings"
                        });
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskAttachments", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolverId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("ReporterId");

                    b.HasIndex("SolverId");

                    b.HasIndex("Status");

                    b.ToTable("TaskItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Contoso",
                            Description = "Login page does not work",
                            DueAt = new DateTime(2026, 3, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            ReportedAt = new DateTime(2026, 2, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            ReporterId = 1,
                            SolverId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Fabrikam",
                            Description = "Email notifications not sent",
                            DueAt = new DateTime(2026, 2, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            ReportedAt = new DateTime(2026, 2, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            ReporterId = 3,
                            SolverId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Northwind",
                            Description = "Update address on invoice template",
                            DueAt = new DateTime(2026, 2, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            ReportedAt = new DateTime(2026, 2, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            ReporterId = 1,
                            ResolvedAt = new DateTime(2026, 2, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            SolverId = 3,
                            Status = 3
                        });
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskMessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Users report that login fails with error 500",
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Investigating the issue",
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2026, 2, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Message = "It stopped sending emails after last deployment.",
                            TaskItemId = 2
                        });
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Alice Admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Bob Solver"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Charlie Tester"
                        });
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("Helpdesk.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskAttachment", b =>
                {
                    b.HasOne("Helpdesk.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Helpdesk.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpdesk.Domain.Entities.User", "Solver")
                        .WithMany()
                        .HasForeignKey("SolverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Solver");
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskMessage", b =>
                {
                    b.HasOne("Helpdesk.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpdesk.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Messages")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Helpdesk.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChecklistItems");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
